version: '3'

services:
  django_app:
    build: .
    # entrypoint: entrypoint.sh
    env_file:
        - .env
    volumes:
      - static_vol:/chatroom/staticfiles
      - media_vol:/chatroom/media
    ports:
      - "8000:8000"
    restart: unless-stopped

  
  nginx:
    build: ./nginx
    volumes:
      - static_vol:/chatroom/staticfiles
      - media_vol:/chatroom/media
    ports:
      - "80:80"
    depends_on:
      - django_app
    restart: unless-stopped

volumes:
  static_vol:
  media_vol:
