version: '3'

services:
  django_app:
    image: changzongchun/django_app_image:latest
    build: .
    # entrypoint: entrypoint.sh
    env_file:
        - .env
    volumes:
      - static_vol:/chatroom/staticfiles
      - media_vol:/chatroom/media
    ports:
      - "8000:8000"

  
  nginx:
    image: changzongchun/nginx_image:latest
    build: ./nginx
    volumes:
      - static_vol:/chatroom/staticfiles
      - media_vol:/chatroom/media
    ports:
      - "80:80"
    depends_on:
      - django_app

volumes:
  static_vol:
  media_vol:
