version: '3'

services:
  django_app:
    image: changzongchun/django_image:latest
    # pull_policy: always
    build: .
    entrypoint: entrypoint.sh
    # environment:
    #   - SECRET_KEY=${SECRET_KEY}
    #   - DEBUG=${DEBUG_MODE}
    #   - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    #   - DB_NAME=${RDS_DBNAME}
    #   - DB_USER=${RDS_USERNAME}
    #   - DB_PASSWORD=${RDS_PASSWORD}
    #   - DB_HOST=${RDS_HOST}
    volumes:
      - static_vol:/chatroom/staticfiles
      - media_vol:/chatroom/media
    ports:
      - "8000:8000"
    restart: unless-stopped
    

  
  nginx:
    image: changzongchun/nginx_image:latest
    # pull_policy: always
    build: ./nginx
    volumes:
      - static_vol:/chatroom/staticfiles
      - media_vol:/chatroom/media
    ports:
      - "80:80"
    depends_on:
      - django_app
    restart: unless-stopped
    

volumes:
  static_vol:
  media_vol:
