name: 'Deploy Docker to AWS (EC2)'
# description: 'Deploy a Docker app to an AWS Virtual Machine (EC2) with Docker Compose'

on:
  push:
    branches: [ master ]



jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: django_image
          - dockerfile: ./nginx/Dockerfile
            image: nginx_image

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      

    - name: Login Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    # - name: Build and Push Docker image
    #   run: |
    #     docker compose build
    #     docker compose push
    #   env:
    #     DOCKER_BUILDKIT: 1  # Enable BuildKit for faster builds


    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}
        flavor: |
          latest=true

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}


    - name: List images in github server
      run: docker image ls -a




  deploy:
    needs: build 
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_NGINX: ${{ secrets.DOCKERHUB_USERNAME }}/nginx_image
      IMAGE_NAME_DJANGO: ${{ secrets.DOCKERHUB_USERNAME }}/django_image

    steps:
    - name: Configure env
      run: |
        cat << EOF > .env-gh
        SECRET_KEY=${{ secrets.SECRET_KEY}}
        DEBUG=False
        ALLOWED_HOSTS= .127.0.0.1, .localhost, .18.183.74.175, 52.194.192.146
        DB_NAME=${{secrets.RDS_DBNAME}}
        DB_USER=${{secrets.RDS_USERNAME}}
        DB_PASSWORD=${{secrets.RDS_PASSWORD}}
        DB_HOST=${{secrets.RDS_HOST}}
        EOF
        ls

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

        # Add the host key of your EC2 instance to known_hosts
        ssh-keyscan ec2-52-194-192-146.ap-northeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts
  

    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/id_rsa .env-gh ubuntu@ec2-52-194-192-146.ap-northeast-1.compute.amazonaws.com \
        ssh -i ~/.ssh/id_rsa  \
        ubuntu@ec2-52-194-192-146.ap-northeast-1.compute.amazonaws.com \
        IMAGE_NAME_DJANGO="${{ env.IMAGE_NAME_DJANGO }}" \
        IMAGE_NAME_NGINX="${{ env.IMAGE_NAME_NGINX }}" \
        '  
        docker login
        docker pull $IMAGE_NAME_DJANGO
        docker pull $IMAGE_NAME_NGINX
        docker image ls -a 
        docker run -d  --network host $IMAGE_NAME_NGINX
        docker run -d --env-file .env-gh --network host $IMAGE_NAME_DJANGO
        '
      # docker compose down || true
      # docker compose pull
      # docker compose -f docker-compose.yml up -d
