name: 'Deploy Docker to AWS (EC2)'
# description: 'Deploy a Docker app to an AWS Virtual Machine (EC2) with Docker Compose'

on:
  push:
    branches: [ dev-v1.0.1 ]

jobs:

  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

      
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - name: Build and Push Docker image
      run: |
        docker-compose build
        docker-compose push
      env:
        DOCKER_BUILDKIT: 1  # Enable BuildKit for faster builds
    

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
  

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa  \
        -o UserKnownHostsFile=/github/home/.ssh/known_hosts -tt \
        ubuntu@ec2-18-183-74-175.ap-northeast-1.compute.amazonaws.com \
        'cd django-chat-room/ && \
        docker-compose down || true && \
        docker-compose pull && \
        docker-compose up -d'
    
 