name: 'Deploy Docker to AWS (EC2)'
# description: 'Deploy a Docker app to an AWS Virtual Machine (EC2) with Docker Compose'

on:
  push:
    branches: [ master ]



jobs:

  build:
    runs-on: ubuntu-latest
    environment: chatroom

    strategy:
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: nginx_image
          - dockerfile: ./nginx/Dockerfile
            image: django_image

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


    - name: Read environment
      run: echo "My secret is ${{ secrets.RDS_DBNAME}}"
      

    - name: Login Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    # - name: Build and Push Docker image
    #   run: |
    #     docker compose build
    #     docker compose push
    #   env:
    #     DOCKER_BUILDKIT: 1  # Enable BuildKit for faster builds


    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}
        flavor: |
          latest=true


    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}



    - name: List images in github server
      run: docker images ls

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_NGINX: ${{ secrets.DOCKERHUB_USERNAME }}/nginx_image
      IMAGE_NAME_DJANGO: ${{ secrets.DOCKERHUB_USERNAME }}/django_image

    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

        # Add the host key of your EC2 instance to known_hosts
        ssh-keyscan ec2-18-183-74-175.ap-northeast-1.compute.amazonaws.com >> ~/.ssh/known_hosts
  

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa  \
        ubuntu@ec2-18-183-74-175.ap-northeast-1.compute.amazonaws.com \
        'bash -s' << 'EOF'

        cd django-chat-room/  
        docker images ls -a 
        docker pull $IMAGE_NAME_DJANGO
        docker pull $IMAGE_NAME_NGINX
        
        EOF
