name: 'Deploy Docker to AWS (EC2)'
# description: 'Deploy a Docker app to an AWS Virtual Machine (EC2) with Docker Compose'

on:
  push:
    branches: [ dev-v1.0.1 ]

jobs:

  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build and Push Docker image
      run: |
        docker-compose build
        docker-compose push

      env:
        DOCKER_BUILDKIT: 1  # Enable BuildKit for faster builds
    
    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

    - name: Deploy
      run: |
        ssh -o "StrictHostKeyChecking no" \
        -i ~/.ssh/id_rsa  \
        ubuntu@ec2-18-183-74-175.ap-northeast-1.compute.amazonaws.com \
        'cd django-chat-room/ && \
        docker-compose pull && \
        docker-compose up -d'
    
 